spring.application.name=thymeleaf_demo
# Data Source URL: Replace 'your_database_name' if needed
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# Database username
spring.datasource.username=postgres
# Database password
spring.datasource.password=profjoe
# indicating the driver class as postgreSQL driver class
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
# spring.security.user.name=jay
# spring.security.user.password=jay
jwt.secret=67bc102072be41a49f7469a61d881ad4
jwt.expiration=3600000
server.servlet.context-path=/myapp
